# Generated by Django 2.2.4 on 2019-08-22 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='application',
        ),
        migrations.AddField(
            model_name='rushee',
            name='responses',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.AddField(
            model_name='comment',
            name='rushee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rush.Rushee'),
        ),
    ]
