# Generated by Django 2.2.4 on 2019-08-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0002_auto_20190822_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='rushee',
            name='random_id',
            field=models.IntegerField(default=66.97072375588675),
        ),
    ]
