# Generated by Django 2.2.4 on 2019-08-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0003_rushee_random_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushee',
            name='random_id',
            field=models.IntegerField(default=381),
        ),
    ]
