# Generated by Django 2.2.4 on 2019-08-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0005_auto_20190822_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='rushee',
            name='username',
            field=models.CharField(default='username959', max_length=100),
        ),
        migrations.AlterField(
            model_name='rushee',
            name='random_id',
            field=models.IntegerField(default=162),
        ),
    ]
