# Generated by Django 2.2.4 on 2019-08-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0007_auto_20190822_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushee',
            name='random_id',
            field=models.IntegerField(default=861),
        ),
        migrations.AlterField(
            model_name='rushee',
            name='username',
            field=models.CharField(default='username626', max_length=100),
        ),
    ]
