# Generated by Django 2.2.4 on 2019-08-23 01:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0008_auto_20190822_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='rushee',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/texasakpsi/image/upload/c_thumb,w_200,g_face/v1566281324/profile_pics/blank-profile-picture_twrtwg.png', max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='rushee',
            name='random_id',
            field=models.IntegerField(default=541),
        ),
        migrations.AlterField(
            model_name='rushee',
            name='username',
            field=models.CharField(default='username957', max_length=100),
        ),
    ]
