# Generated by Django 2.2.4 on 2019-08-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0009_auto_20190822_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushee',
            name='random_id',
            field=models.IntegerField(default=504),
        ),
        migrations.AlterField(
            model_name='rushee',
            name='username',
            field=models.CharField(default='username368', max_length=100),
        ),
    ]
