# Generated by Django 2.2.4 on 2019-08-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0010_auto_20190822_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='rushee',
            name='college_year_selection',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Freshman'), (1, 'Sophomore'), (2, 'Junior'), (3, 'Senior'), (4, 'Graduate')], default=0),
        ),
        migrations.AlterField(
            model_name='rushee',
            name='random_id',
            field=models.IntegerField(default=871),
        ),
        migrations.AlterField(
            model_name='rushee',
            name='username',
            field=models.CharField(default='username151', max_length=100),
        ),
    ]
