# Generated by Django 2.2.4 on 2019-08-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0013_auto_20190827_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushee',
            name='random_id',
            field=models.IntegerField(default=414),
        ),
        migrations.AlterField(
            model_name='rushee',
            name='username',
            field=models.CharField(default='username273', max_length=100),
        ),
    ]
