# Generated by Django 2.2.4 on 2019-08-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0016_auto_20190827_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rushee',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='rushee',
            name='number_of_votes',
        ),
        migrations.AddField(
            model_name='rushee',
            name='no_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rushee',
            name='yes_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rushee',
            name='random_id',
            field=models.IntegerField(default=231),
        ),
        migrations.AlterField(
            model_name='rushee',
            name='username',
            field=models.CharField(default='username83', max_length=100),
        ),
    ]
