# Generated by Django 2.2.4 on 2019-09-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0020_auto_20190909_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rushee',
            name='no_votes',
        ),
        migrations.RemoveField(
            model_name='rushee',
            name='yes_votes',
        ),
        migrations.AddField(
            model_name='rushee',
            name='aggregate_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rushee',
            name='num_of_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rushee',
            name='random_id',
            field=models.IntegerField(default=263),
        ),
        migrations.AlterField(
            model_name='rushee',
            name='username',
            field=models.CharField(default='username584', max_length=100),
        ),
    ]
