# Generated by Django 2.2.4 on 2019-09-10 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0023_auto_20190909_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushee',
            name='date_of_application',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rushee',
            name='random_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rushee',
            name='username',
            field=models.CharField(default='username927', max_length=100),
        ),
    ]
