# Generated by Django 2.2.4 on 2019-09-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0024_auto_20190910_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rushee',
            name='username',
            field=models.CharField(default='username201', max_length=100),
        ),
    ]
