# Generated by Django 2.2.4 on 2019-08-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20190819_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(default='utakpsi@gmail.com'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(default='John'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.TextField(default='Doe'),
        ),
    ]
