# Generated by Django 2.2.4 on 2019-08-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20190819_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college_year_selection',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Freshman'), (1, 'Sophomore'), (2, 'Junior'), (3, 'Senior'), (4, 'Graduate')], default=0),
        ),
    ]
