# Generated by Django 2.2.4 on 2019-08-20 05:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20190819_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img_file',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
