# Generated by Django 2.2.4 on 2019-08-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_profile_img_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img_file',
        ),
    ]
