# Generated by Django 2.2.4 on 2019-08-20 06:20

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/texasakpsi/image/upload/v1566281324/profile_pics/blank-profile-picture_twrtwg.png', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mysite.ProfilePic'),
        ),
    ]
