# Generated by Django 2.2.4 on 2019-08-20 06:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20190820_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='image_file',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/texasakpsi/image/upload/v1566281324/profile_pics/blank-profile-picture_twrtwg.png', max_length=255, verbose_name='image'),
        ),
    ]
