# Generated by Django 2.2.4 on 2019-08-20 06:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_remove_profile_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/texasakpsi/image/upload/c_thumb,w_200,g_face/v1566281324/profile_pics/blank-profile-picture_twrtwg.png', max_length=255, verbose_name='image'),
        ),
    ]
