# Generated by Django 2.2.4 on 2019-08-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
