# Generated by Django 2.2.4 on 2019-08-27 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_auto_20190820_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
