# Generated by Django 2.2.4 on 2019-08-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0017_auto_20190830_1359'),
        ('mysite', '0021_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='votes',
            field=models.ManyToManyField(to='rush.Rushee'),
        ),
    ]
