# Generated by Django 2.2.4 on 2019-09-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_profile_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='votes',
            field=models.ManyToManyField(blank=True, to='rush.Rushee'),
        ),
    ]
